name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Laravel backend image
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: your-docker-repo/laravel-backend:latest

    - name: Build and push Vue.js frontend image
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: your-docker-repo/vue-frontend:latest

    - name: Deploy to AKS
      uses: azure/k8s-deploy@v1
      with:
        action: deploy
        manifests: |
          ./k8s/laravel-backend-deployment.yaml
          ./k8s/vue-frontend-deployment.yaml
        images: |
          your-docker-repo/laravel-backend:latest
          your-docker-repo/vue-frontend:latest
